# Generated by Django 4.0 on 2024-11-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('science', '科学のこと'), ('dailylife', '日常のこと'), ('music', '音楽のこと')], max_length=50, verbose_name='カテゴリ'),
        ),
    ]
